name: nix-flake-check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: docker
    container:
      image: nixos/nix:2.26.1
    steps:
      - uses: actions/checkout@v4

      - name: Run flake check
        run: |
          export NIX_CONFIG="experimental-features = nix-command flakes"
          nix flake check --no-build
